// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace CodeMazeProject1.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250122170250_initialCreation")]
    partial class initialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<Guid>("CompanyGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Company Guid");

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyGuid");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyGuid = new Guid("c9d4c053-49b0-4a8c-8e0d-3b5f5f6f6f9b"),
                            CompanyAddress = "583 Wall Dr. Gwynn Oak, MD 21207",
                            CompanyName = "IT Solutions Ltd",
                            Country = "United States"
                        },
                        new
                        {
                            CompanyGuid = new Guid("d8e506f1-1d3f-4b3f-8f0a-2f3f6f6f6f9b"),
                            CompanyAddress = "312 Forest Avenue, BF 923",
                            CompanyName = "Admin Solutions Ltd",
                            Country = "United States"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Employee Guid");

                    b.Property<Guid>("CompanyGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EmployeeAge")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EmployeePosition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeGuid");

                    b.HasIndex("CompanyGuid");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeGuid = new Guid("80abbca8-664d-4b20-b5de-024705497d4a"),
                            CompanyGuid = new Guid("c9d4c053-49b0-4a8c-8e0d-3b5f5f6f6f9b"),
                            EmployeeAge = 26,
                            EmployeeName = "Sam Raiden",
                            EmployeePosition = "Software developer"
                        },
                        new
                        {
                            EmployeeGuid = new Guid("86dba8c0-d178-41e7-938c-ed49778fb52a"),
                            CompanyGuid = new Guid("c9d4c053-49b0-4a8c-8e0d-3b5f5f6f6f9b"),
                            EmployeeAge = 30,
                            EmployeeName = "Jana McLeaf",
                            EmployeePosition = "Software developer"
                        },
                        new
                        {
                            EmployeeGuid = new Guid("021ca3c1-0deb-4afd-ae94-2159a8479811"),
                            CompanyGuid = new Guid("d8e506f1-1d3f-4b3f-8f0a-2f3f6f6f6f9b"),
                            EmployeeAge = 35,
                            EmployeeName = "Kane Miller",
                            EmployeePosition = "Administrator"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
